### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by paithiov909** [paithiov909/RcppMeCab#3]
## Refactoring

- [ ] Vectorize non parallel C++ funcitons and simplify function calls from R side.
- [ ] Use `mecab_model_new2` instead of `mecab_model_new`
- [ ] Reserve vector size to which the functions push back values beforehand
- [ ] Make tests more specific
- [ ] Add macOS-latest run to GitHubActions CI

## Changes

- Fix the behavior when input sentence is a named vector (merged from the [commit](https://github.com/paithiov909/RcppMeCab/pull/2/commits/2027ea78e01f81b5d814c891630323f189a857f7) by koheiw)
- Add RcppThread and some other dependencies
- Add `posSimple` function, pack function and other 2 utils

## TODO?

- Add a parallel version of `posSimple`
